export const regions: Record<string, string> = {
  sfo1: "San Francisco, USA",
  iad1: "Washington, D.C., USA",
  pdx1: "Portland, USA",
  cle1: "Cleveland, USA",
  gru1: "São Paulo, Brazil",
  hkg1: "Hong Kong",
  hnd1: "Tokyo, Japan",
  icn1: "Seoul, South Korea",
  kix1: "Osaka, Japan",
  sin1: "Singapore",
  bom1: "Mumbai, India",
  syd1: "Sydney, Australia",
  cdg1: "Paris, France",
  arn1: "Stockholm, Sweden",
  dub1: "Dublin, Ireland",
  lhr1: "London, United Kingdom",
  fra1: "Frankfurt, Germany",
  cpt1: "Cape Town, South Africa",
};
